export const authActions = {
  //Logout
  LOGOUT: "LOGOUT",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_ERROR: "LOGOUT_ERROR",

  //Login Actions
  LOGIN: "LOGIN",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_ERROR: "LOGIN_ERROR",
  LOGIN_INVALID: "LOGIN_INVALID",

  CLEAR_LOGIN_ERROR: "CLEAR_LOGIN_ERROR",

  //Forgot Password Actions
  FORGOT_PASSWORD: "FORGOT_PASSWORD",
  FORGOT_PASSWORD_SUCCESS: "FORGOT_PASSWORD_SUCCESS",
  FORGOT_PASSWORD_ERROR: "FORGOT_PASSWORD_ERROR",
  FORGOT_PASSWORD_INVALID_EMAIL_ERROR: "FORGOT_PASSWORD_INVALID_EMAIL_ERROR",

  CLEAR_FORGOT_PASSWORD_STATE: "CLEAR_FORGOT_PASSWORD_STATE",
  CLEAR_FORGOT_PASSWORD_ERROR: "CLEAR_FORGOT_PASSWORD_ERROR",

  //Reset Password Error
  RESET_PASSWORD: "RESET_PASSWORD",
  RESET_PASSWORD_SUCCESS: "RESET_PASSWORD_SUCCESS",
  RESET_PASSWORD_ERROR: "RESET_PASSWORD_ERROR",
  RESET_PASSWORD_INVALID: "RESET_PASSWORD_INVALID",

  CLEAR_RESET_PASSWORD_STATE: "CLEAR_RESET_PASSWORD_STATE",
  CLEAR_RESET_PASSWORD_ERROR: "CLEAR_RESET_PASSWORD_ERROR",

  //Get email address for resetting the password
  GET_EMAIL_ADDRESS: "GET_EMAIL_ADDRESS",
  GET_EMAIL_ADDRESS_SUCCESS: "GET_EMAIL_ADDRESS_SUCCESS",
  GET_EMAIL_EXPIRED: "GET_EMAIL_EXPIRED",
  GET_EMAIL_ADDRESS_ERROR: "GET_EMAIL_ADDRESS_ERROR",

  //Change Password
  CHANGE_PASSWORD: "CHANGE_PASSWORD",
  CHANGE_PASSWORD_SUCCESS: "CHANGE_PASSWORD_SUCCESS",
  CHANGE_PASSWORD_ERROR: "CHANGE_PASSWORD_ERROR",
  CHANGE_PASSWORD_INVALID: "CHANGE_PASSWORD_INVALID",
  CLEAR_CHANGE_PASSWORD_ERROR: "CLEAR_CHANGE_PASSWORD_ERROR",

  //Getting User Profile Data
  GET_USER_DETAILS: "GET_USER_DETAILS",
  USER_DETAILS: "USER_DETAILS",
  USER_DETAILS_ERROR: "USER_DETAILS_ERROR",
  USER_DETAILS_INVALID: "USER_DETAILS_INVALID",

  //Update User Profile
  USER_UPDATE: "USER_UPDATE",
  USER_UPDATE_SUCCESS: "USER_UPDATE_SUCCESS",
  USER_UPDATE_ERROR: "USER_UPDATE_ERROR",
  USER_UPDATE_INVALID: "USER_UPDATE_INVALID",
  CLEAR_USER_UPDATE_ERROR: "CLEAR_USER_UPDATE_ERROR",

  CREATE_REGISTER_USER: "CREATE_REGISTER_USER",
  CREATE_REGISTER_USER_SUCCESS: "CREATE_REGISTER_USER_SUCCESS",
  CREATE_REGISTER_USER_ERROR: "CREATE_REGISTER_USER_ERROR",

  CLEAR_REGISTER_USER: "CLEAR_REGISTER_USER",
};
